packages:
    github.com/Alex322322/short-url/internal/http/server/handlers/url/save:
        interfaces:
            URLSaver:
    github.com/Alex322322/short-url/internal/http/server/handlers/url/redirect:
        interfaces:
            URLGetter:
    github.com/Alex322322/short-url/internal/http/server/handlers/url/delete:
        interfaces:
            URLDeleter: