env: "local" # задаем среду запуска local
storage_path: "./storage/storage.db"
http_server:
  address: "localhost:8084"
  timeout: 5s
  idle_timeout: 120s
  user: "admin"
  password: "${HTTP_SERVER_PASSWORD}" # используем переменную окружения для пароля